before:
  hooks:
    - go build -o numary
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    binary: numary
archives:
  - replacements:
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - image_templates: ["496288716344.dkr.ecr.eu-west-1.amazonaws.com/numary-prod-ecr:{{ .Version }}"]
    dockerfile: Dockerfile
