name: Build for Control
on:
  workflow_call:
    secrets:
      NUMARY_GITHUB_TOKEN:
        required: true
        description: GitHub token with access to the repo

jobs:
  build:
    name: 'Build Control'
    runs-on: ubuntu-latest
    steps:
      - run: curl -OL https://github.com/formancehq/control/archive/refs/tags/v1.9.0-beta.1.tar.gz
      - run: tar -zxvf v1.9.0-beta.1.tar.gz
      - run: rm -rf v1.9.0-beta.1.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: control-dist
          path: ./**
